// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using EDC.Shared.Models;
using Microsoft.EntityFrameworkCore;

namespace EDC.Server.Data;

public partial class DefaultDbContext : DbContext
{
    public DefaultDbContext(DbContextOptions<DefaultDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AreaType> AreaTypes { get; set; }

    public virtual DbSet<Constituency> Constituencies { get; set; }

    public virtual DbSet<District> Districts { get; set; }

    public virtual DbSet<Meeting15nov2024> Meeting15nov2024s { get; set; }

    public virtual DbSet<ParliamentConstituency> ParliamentConstituencies { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AreaType>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("AreaType");

            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<Constituency>(entity =>
        {
            entity.HasOne(d => d.ParliamentConstituencyNoNavigation).WithMany(p => p.Constituencies)
                .HasForeignKey(d => d.ParliamentConstituencyNo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Constituencies_ParliamentConstituencies");
        });

        modelBuilder.Entity<District>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_NewTable");

            entity.ToTable("District");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TamilName).HasMaxLength(50);
        });

        modelBuilder.Entity<Meeting15nov2024>(entity =>
        {
            entity.ToTable("Meeting(15Nov2024)");

            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNo).HasMaxLength(15);
        });

        modelBuilder.Entity<ParliamentConstituency>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_ParilimentConstituencies");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TamilName).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}