// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EDC.Shared.Models;

public partial class Meeting15nov2024
{
    public int Id { get; set; }

    public int? DistrictId { get; set; }

    public int? ParliamentConstituencyId { get; set; }

    public int? ConstituencyId { get; set; }

    public int? AreaTypeId { get; set; }

    public string AreaName { get; set; }

    public int? BoothNo { get; set; }

    public string Name { get; set; }

    public string PhoneNo { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public string Image { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsActive { get; set; }
}